### PR TITLE
Stop overriding $bar

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Review by jeffw16 — APPROVED** [review]
LGTM

**Comment by jeffw16** [comment]
Hang on @paladox, at first I thought this was some cosmetic changes and fixing some huge bug that broke things in newer versions of MW, but this change no longer initializes a new array on the address where $bar is located. Therefore, I've added the following right before $bar has its Login link added to it:

```
$bar = [];
```

**Comment by paladox** [comment]
> Hang on @paladox, while this correctly changes the $bar parameter from pass-by-value to pass-by-reference, this change doesn't initialize a new array on the address where $bar is located. Therefore, I've added the following right before $bar has its Login link added to it:
> 
> ```
> $bar = [];
> ```

See https://www.mediawiki.org/wiki/Manual:Hooks/SkinBuildSidebar

it's already an array so doing = [] is erasing  and replacing.

**Comment by jeffw16** [comment]
Yes that's correct, because we want the sidebar to be hidden, so we do want to delete the existing array so that it isn't shown to anyone who isn't logged in. Is there a specific reason why we shouldn't be doing this?

**Comment by jeffw16** [comment]
Also, the documentation page isn't very helpful; the PHP code is already self-explanatory.

**Pull request merged**
